  replicaCount: 3

  image:
    repository: hasindukarunathilaka/order-service  # Docker Hub repository name
    tag: "latest"  # The tag for Docker image
    pullPolicy: Always

  service:
    type: LoadBalancer  # Service type for external access
    port: 80  # Port to expose the service
    targetPort: 8080

  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

