name: Order Service Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/order-service:latest

      # - name: Install Helm
      #   uses: azure/setup-helm@v3

      # - name: Add Helm repo
      #   run: helm repo add my-helm-repo https://my-helm-repo.example.com  # Replace with your actual Helm chart repository URL

      # - name: Deploy user-service
      #   run: |
      #     helm upgrade --install user-service ./charts/user-service --version 1.0.0 --namespace user-service --create-namespace

      # - name: Deploy order-service
      #   run: |
      #     helm upgrade --install order-service ./charts/order-service --version 1.0.0 --namespace order-service --create-namespace
